name: Cache
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        id: cache-test
        with:
          path: ~/
          key: ${{ runner.os }}-cache-test
          restore-keys: |
            ${{ runner.os }}-cache-

      - run: sleep 5 && echo "Hello world" > ~/1.log
        if: steps.cache-test.outputs.cache-hit != 'true'

      - run: sleep 5 && echo "Hello world" > ~/2.log
        if: steps.cache-test.outputs.cache-hit != 'true'

      - run: cat ~/*.log
