name: Test IF

on:
  workflow_dispatch:
    inputs:
      test-jobs:
        description: '测试 IF'

env:
  ENVIRONMENT: prod

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo The dev env is ${{ env.ENVIRONMENT }}
        if: env.ENVIRONMENT == 'dev'

      - run: echo The prod env is ${{ env.ENVIRONMENT }}
        if: env.ENVIRONMENT == 'prod'
