name: Test Jobs

on:
  workflow_dispatch:
    inputs:
      test-jobs:
        description: '测试 Jobs'


jobs:
  jobs-1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world! This is jobs-1

  jobs-2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world! This is jobs-2

  jobs-3:
    runs-on: ubuntu-latest
    needs:
      - jobs-1
    steps:
      - name: Run a one-line script
        run: echo Hello, world! This is jobs-3, but after jobs-1