name: Redis
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    container: redis

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Run Redis
        run: redis-cli ping